### ISSUE TITLE
Need to update document

### ISSUE THREAD

**Issue by kshestov** [khadas/documents#3]
In file "documents/InstallToolchainsForAmlogicPlatform.md" link to linaro compiler is wrong
Actual is: https://releases.linaro.org/archive/14.09/components/toolchain/binaries/gcc-linaro-aarch64-linux-gnu-4.9-2014.09_linux.tar.bz2

**Comment by numbqq** [comment]
Hi kshestov,

Thanks for your feedback. This repo is out of date, the new documentation is 

https://github.com/khadas/khadas_docs
